### ISSUE TITLE
As a developer, I want Assets to be able to change their location.

### ISSUE THREAD

**Issue by Exonoesis** [Exonoesis/Leviathan-Logic-Engine#18] opened 2021-03-26 08:03 UTC

**Comment by Exonoesis** [comment] 2021-04-16 22:20
### MoveTo() Proposal

This will be a Coroutine within AssetViewer that takes in two parameters; target position and speed.

It will consist of a while loop that utilizes the `Vector3.MoveTowards()` function built into Unity. 

`Vector3.Lerp()` is another option for movement but in the past, I wasn't fond of it visually. I'll likely give Lerp another chance but we'll see how that goes. 

Lerp versus MoveTowards however is a purely cosmetic choice.

---

MoveTo() will also need an interrupt that will cleanly snap the character to the target position. This interrupt could be accomplished by either:

A) Setting the asset's position to the destination.
Pros: Instant.
Cons: Asset would visually teleport, which may not be appealing.

B) Complete the `MoveTowards()` at an accelerated speed.
Pros: Would look smoother than teleporting.
Cons: Frames/Time would pass before movement fully stops.

**Comment by divark** [comment] 2021-04-17 01:03
Some questions before we talk about the implementation options:

1. Where will Asset movement be used? Point and Click scenes? Cutscenes?
2. What are the causes for an Asset to be told to be interrupted, or rather, to "hurry up"?

**Comment by Exonoesis** [comment] 2021-04-17 02:04
1. For the time being only Character Assets are planned to move, so this would be happening exclusively in Cutscenes.
2. If a Character's movement was tied to Dialogue and the Dialogue was interrupted then the attached movement should also be interrupted.

**Comment by divark** [comment] 2021-04-17 17:49
Alright. So, you mentioned there's a visual difference between using Vector3's MoveTowards and Lerp. How do they differ?

Regarding the interrupt approaches, considering that when the Dialogue is interrupted, it immediately brings all text into view. 
- If the goal is to keep consistency, then approach A makes sense. 
- In addition, consider the use case of a player wanting to skip through dialogue quickly. Approach A, while it could be jarring, would be the quickest way to achieve that, while Approach B would seem like the game is struggling to catch up if I'm understanding the cons correctly.

Thoughts?

**Comment by Exonoesis** [comment] 2021-04-17 20:51
MoveTowards moves at a constant speed from start to target. Lerp starts fast then slows down as it approaches the target. There's apparently a third one I just ran into as well called SmoothDamp, it starts slow, goes fast in the middle, then slows down again at the end. They all complete the movement in the exactly same amount of time, so it should be a matter of preference.

I agree that approach A is the better option. Though it will make the characters "snappy" when an interrupt occurs I think it's important that nothing lingers or lags behind in this case. Even if the player is only waiting for a second or two after trying to skip they'll notice that and it'll slow them down when the point of interrupting is to go fast and skip ahead. Since the text displays instantly as well that consistency is not only good for the code but good for the game aesthetic as well, things will be behaving similarly that are linked together.

**Comment by divark** [comment] 2021-04-17 23:54
Okay, then let's stick with approach A for now.

Otherwise, what I find interesting is that we have three choices of movement in mind, each having their own cosmetic value. What are your thoughts on having this MoveTo logic have all three options available? That is, either:
- MoveTo is broken up into `MoveTo`, `MoveToFastStart`, and `MoveToFastMiddle`.
- MoveTo takes an argument specifying what type of movement function to use. Think an `enum` with `Smooth`, `FastStart`, and `FastMiddle`.
- Any other approaches that come to mind.

**Comment by Exonoesis** [comment] 2021-04-18 01:57
I would prefer MoveTo to take an argument for the type of movement since the code itself is going to be very similar for each. 

Example
`transform.position = Vector3.MoveTowards(transform.position, target.position, speed * Time.deltaTime);`
`transform.position = Vector3.Lerp(transform.position, target.position, speed * Time.deltaTime);`
`transform.position = Vector3.SmoothDamp(transform.position, target.position, ref velocity, speed * Time.deltaTime);`

The only difference is that SmoothDamp takes a velocity vector, which could be declared as a private local variable within the function. Otherwise, they all need a reference to the current position, the target position, and the speed. Would you suggest a switch statement on the enum type since there are only three of them?

**Comment by divark** [comment] 2021-04-18 02:49
Yes, a switch statement would be preferred, especially if these items have less than five lines worth of changes for each.

Finally, what are the new expected features to be tested, if any? Rather, what new tests will be introduced, and which existing tests will change?

**Comment by Exonoesis** [comment] 2021-04-18 21:19
Given that there are three types of movement being implemented I would want at least one new test for each within AssetViewerTests.

- [ ] MoveToMoveTowards
- [ ] MoveToLerp
- [ ] MoveToSmoothDamp

In which an Asset would be placed at a location in the Scene and then use the given movement method to arrive at a designated location. We would then simply assert the Asset's position is the desired position. The Scene type should be arbitrary and have no effect on the tests but I was thinking to divide each test into two parts, one with a Cutscene and one with a Point & Click. Is that overtesting?

I would also like a test of the interrupt of each, however, we currently don't have a way to invoke an interrupt without mouse input. This would warrant another interactive test akin to our SceneTrasitionTests. Rather than being inconclusive, it would check the position of the Asset at the end.

- [ ] MovementInterrupt 

However, given that we don't have a test for Dialogue interrupts I'm unsure if this test is necessary.

**Comment by divark** [comment] 2021-04-18 22:57
Given that this Asset movement should work regardless of the Scene, I'd say that this isn't considered overtesting.

As for the MovementInterrupt consideration, it best fits in SceneTransitionTests, since it involves observing cosmetic behavior that we have yet to capture with asserts.

Otherwise, this looks like it's Design Ready. What do you think?

**Comment by Exonoesis** [comment] 2021-04-19 20:01
Just a few clarifications. 

So you're saying I should include a Cutscene and Point & Click test for each type of movement? If so, should they be individual tests or could I combine them? For example, in MoveToLerp it would test Lerp movement in a Cutscene and then a Point & Click within the same test and only pass if both cases pass. The alternative is that there would be a MoveToLerpCutscene and a MoveToLerpP&C that would run individually and pass independently.

Also, while I agree that the interrupt is mostly cosmetic, there's still a valid concern if the Asset will be in the given position when an interrupt occurs. As opposed to something silly like freezing in place mid-movement. I would like to have two tests within `SceneTransitionTests` that contain asserts.

- [ ] MovementInterrupt
- [ ] DialogueInterrupt

The second test stemming from it coming to my attention that there's no check for accuracy for the interrupt of the Teletype function.

**Comment by divark** [comment] 2021-04-19 22:19
What are your thoughts on having each type of movement incorporating all Scene types within it? For example, say `MoveToLerp` would have a collection of all Scene types. Each Scene would be shown the same way, and Assets for them would be tracked to see if they move properly.

Otherwise, that sounds like a good idea including the Movement and Dialogue interrupt within the `SceneTrasnitionTests`.

**Comment by Exonoesis** [comment] 2021-04-20 18:46
I think a collection of Scenes that we iterate through will keep things easily scalable given that there may be many types of Scenes with Assets in the future. The logic wouldn't need to change for future Scenes nor would it grow with the number of Scenes; it simply would do more iterations. 

With that, I will say this feature is Design Ready.

**Closed** 2021-05-04 03:25 UTC
Labels: enhancement
